/* Generated by Yosys 0.53+15 (git sha1 690081810, g++ 14.2.1_p20241221 -fPIC -O3) */

module \$paramod$186f8b1d6efc0393fac387b94511cf8204761fbf\ctrl_block (VGND, VDPWR, clk, rst_n, enable, data_in, data_out, ctrl_out);
  input VDPWR;
  wire VDPWR;
  input VGND;
  wire VGND;
  input clk;
  wire clk;
  output [1:0] ctrl_out;
  wire [1:0] ctrl_out;
  input data_in;
  wire data_in;
  output data_out;
  wire data_out;
  input enable;
  wire enable;
  wire l_clk;
  wire l_enable;
  wire l_rst_n;
  input rst_n;
  wire rst_n;
  wire [2:0] shift;
  sky130_fd_sc_hd__clkbuf_4 \buf_I[0]  (
    .A(enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_enable)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[1]  (
    .A(rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_rst_n)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[2]  (
    .A(clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_clk)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[0]  (
    .CLK(l_clk),
    .D(shift[0]),
    .Q(shift[1]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[1]  (
    .CLK(l_clk),
    .D(shift[1]),
    .Q(shift[2]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__clkdlybuf4s50_2 \genblk2.out_dly  (
    .A(shift[2]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(data_out)
  );
  sky130_fd_sc_hd__and2_2 \mask_I[0]  (
    .A(shift[1]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[0])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[1]  (
    .A(shift[2]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[1])
  );
  assign shift[0] = data_in;
endmodule

module \$paramod$4c429810042df638a787709115c70023fe8679c2\ctrl_block (VGND, VDPWR, clk, rst_n, enable, data_in, data_out, ctrl_out);
  input VDPWR;
  wire VDPWR;
  input VGND;
  wire VGND;
  input clk;
  wire clk;
  output [7:0] ctrl_out;
  wire [7:0] ctrl_out;
  input data_in;
  wire data_in;
  output data_out;
  wire data_out;
  input enable;
  wire enable;
  wire l_clk;
  wire l_enable;
  wire l_rst_n;
  input rst_n;
  wire rst_n;
  wire [8:0] shift;
  sky130_fd_sc_hd__clkbuf_4 \buf_I[0]  (
    .A(enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_enable)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[1]  (
    .A(rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_rst_n)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[2]  (
    .A(clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_clk)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[0]  (
    .CLK(l_clk),
    .D(shift[0]),
    .Q(shift[1]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[1]  (
    .CLK(l_clk),
    .D(shift[1]),
    .Q(shift[2]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[2]  (
    .CLK(l_clk),
    .D(shift[2]),
    .Q(shift[3]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[3]  (
    .CLK(l_clk),
    .D(shift[3]),
    .Q(shift[4]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[4]  (
    .CLK(l_clk),
    .D(shift[4]),
    .Q(shift[5]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[5]  (
    .CLK(l_clk),
    .D(shift[5]),
    .Q(shift[6]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[6]  (
    .CLK(l_clk),
    .D(shift[6]),
    .Q(shift[7]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[7]  (
    .CLK(l_clk),
    .D(shift[7]),
    .Q(shift[8]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__clkdlybuf4s50_2 \genblk2.out_dly  (
    .A(shift[8]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(data_out)
  );
  sky130_fd_sc_hd__and2_2 \mask_I[0]  (
    .A(shift[1]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[0])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[1]  (
    .A(shift[2]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[1])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[2]  (
    .A(shift[3]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[2])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[3]  (
    .A(shift[4]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[3])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[4]  (
    .A(shift[5]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[4])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[5]  (
    .A(shift[6]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[5])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[6]  (
    .A(shift[7]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[6])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[7]  (
    .A(shift[8]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[7])
  );
  assign shift[0] = data_in;
endmodule

module \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block (VGND, VDPWR, clk, rst_n, enable, data_in, data_out, ctrl_out);
  input VDPWR;
  wire VDPWR;
  input VGND;
  wire VGND;
  input clk;
  wire clk;
  output [5:0] ctrl_out;
  wire [5:0] ctrl_out;
  input data_in;
  wire data_in;
  output data_out;
  wire data_out;
  input enable;
  wire enable;
  wire l_clk;
  wire l_enable;
  wire l_rst_n;
  input rst_n;
  wire rst_n;
  wire [6:0] shift;
  sky130_fd_sc_hd__clkbuf_4 \buf_I[0]  (
    .A(enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_enable)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[1]  (
    .A(rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_rst_n)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[2]  (
    .A(clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_clk)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[0]  (
    .CLK(l_clk),
    .D(shift[0]),
    .Q(shift[1]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[1]  (
    .CLK(l_clk),
    .D(shift[1]),
    .Q(shift[2]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[2]  (
    .CLK(l_clk),
    .D(shift[2]),
    .Q(shift[3]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[3]  (
    .CLK(l_clk),
    .D(shift[3]),
    .Q(shift[4]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[4]  (
    .CLK(l_clk),
    .D(shift[4]),
    .Q(shift[5]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[5]  (
    .CLK(l_clk),
    .D(shift[5]),
    .Q(shift[6]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__clkdlybuf4s50_2 \genblk1.in_dly  (
    .A(data_in),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(shift[0])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[0]  (
    .A(shift[1]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[0])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[1]  (
    .A(shift[2]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[1])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[2]  (
    .A(shift[3]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[2])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[3]  (
    .A(shift[4]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[3])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[4]  (
    .A(shift[5]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[4])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[5]  (
    .A(shift[6]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[5])
  );
  assign data_out = shift[6];
endmodule

module \$paramod$8070f2d037679cd31e5ac6f078a5f8019a69e436\ctrl_block (VGND, VDPWR, clk, rst_n, enable, data_in, data_out, ctrl_out);
  input VDPWR;
  wire VDPWR;
  input VGND;
  wire VGND;
  input clk;
  wire clk;
  output [3:0] ctrl_out;
  wire [3:0] ctrl_out;
  input data_in;
  wire data_in;
  output data_out;
  wire data_out;
  input enable;
  wire enable;
  wire l_clk;
  wire l_enable;
  wire l_rst_n;
  input rst_n;
  wire rst_n;
  wire [4:0] shift;
  sky130_fd_sc_hd__clkbuf_4 \buf_I[0]  (
    .A(enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_enable)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[1]  (
    .A(rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_rst_n)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[2]  (
    .A(clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_clk)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[0]  (
    .CLK(l_clk),
    .D(shift[0]),
    .Q(shift[1]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[1]  (
    .CLK(l_clk),
    .D(shift[1]),
    .Q(shift[2]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[2]  (
    .CLK(l_clk),
    .D(shift[2]),
    .Q(shift[3]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[3]  (
    .CLK(l_clk),
    .D(shift[3]),
    .Q(shift[4]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__clkdlybuf4s50_2 \genblk2.out_dly  (
    .A(shift[4]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(data_out)
  );
  sky130_fd_sc_hd__and2_2 \mask_I[0]  (
    .A(shift[1]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[0])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[1]  (
    .A(shift[2]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[1])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[2]  (
    .A(shift[3]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[2])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[3]  (
    .A(shift[4]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[3])
  );
  assign shift[0] = data_in;
endmodule

module \$paramod$9347947338dd2dfd9e49dd4a7c49f3c6949c9061\ctrl_block (VGND, VDPWR, clk, rst_n, enable, data_in, data_out, ctrl_out);
  input VDPWR;
  wire VDPWR;
  input VGND;
  wire VGND;
  input clk;
  wire clk;
  output [5:0] ctrl_out;
  wire [5:0] ctrl_out;
  input data_in;
  wire data_in;
  output data_out;
  wire data_out;
  input enable;
  wire enable;
  wire l_clk;
  wire l_enable;
  wire l_rst_n;
  input rst_n;
  wire rst_n;
  wire [6:0] shift;
  sky130_fd_sc_hd__clkbuf_4 \buf_I[0]  (
    .A(enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_enable)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[1]  (
    .A(rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_rst_n)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_I[2]  (
    .A(clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(l_clk)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[0]  (
    .CLK(l_clk),
    .D(shift[0]),
    .Q(shift[1]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[1]  (
    .CLK(l_clk),
    .D(shift[1]),
    .Q(shift[2]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[2]  (
    .CLK(l_clk),
    .D(shift[2]),
    .Q(shift[3]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[3]  (
    .CLK(l_clk),
    .D(shift[3]),
    .Q(shift[4]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[4]  (
    .CLK(l_clk),
    .D(shift[4]),
    .Q(shift[5]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__dfrtp_1 \ff_I[5]  (
    .CLK(l_clk),
    .D(shift[5]),
    .Q(shift[6]),
    .RESET_B(l_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__clkdlybuf4s50_2 \genblk2.out_dly  (
    .A(shift[6]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(data_out)
  );
  sky130_fd_sc_hd__and2_2 \mask_I[0]  (
    .A(shift[1]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[0])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[1]  (
    .A(shift[2]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[1])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[2]  (
    .A(shift[3]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[2])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[3]  (
    .A(shift[4]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[3])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[4]  (
    .A(shift[5]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[4])
  );
  sky130_fd_sc_hd__and2_2 \mask_I[5]  (
    .A(shift[6]),
    .B(l_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(ctrl_out[5])
  );
  assign shift[0] = data_in;
endmodule

module ctrl_top(VGND, VDPWR, clk, rst_n, enable, data_in, data_out, ctrl_out);
  input VDPWR;
  wire VDPWR;
  input VGND;
  wire VGND;
  wire [26:0] asw_data;
  input clk;
  wire clk;
  output [191:0] ctrl_out;
  wire [191:0] ctrl_out;
  input data_in;
  wire data_in;
  output data_out;
  wire data_out;
  wire [7:0] dev_data;
  input enable;
  wire enable;
  wire g_clk;
  wire g_enable;
  wire g_rst_n;
  wire [1:0] mid_data;
  input rst_n;
  wire rst_n;
  \$paramod$4c429810042df638a787709115c70023fe8679c2\ctrl_block  blk_nmos_cm_I (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[183:176]),
    .data_in(dev_data[4]),
    .data_out(dev_data[5]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  \$paramod$8070f2d037679cd31e5ac6f078a5f8019a69e436\ctrl_block  blk_nmos_dp_I (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[175:172]),
    .data_in(dev_data[3]),
    .data_out(dev_data[4]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  \$paramod$9347947338dd2dfd9e49dd4a7c49f3c6949c9061\ctrl_block  blk_nmos_dual_I (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[189:184]),
    .data_in(dev_data[5]),
    .data_out(dev_data[6]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  \$paramod$186f8b1d6efc0393fac387b94511cf8204761fbf\ctrl_block  blk_nmos_ota_I (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[191:190]),
    .data_in(dev_data[6]),
    .data_out(dev_data[7]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  \$paramod$9347947338dd2dfd9e49dd4a7c49f3c6949c9061\ctrl_block  blk_pmos_cm_I (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[167:162]),
    .data_in(dev_data[1]),
    .data_out(dev_data[2]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  \$paramod$8070f2d037679cd31e5ac6f078a5f8019a69e436\ctrl_block  blk_pmos_dp_I (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[171:168]),
    .data_in(dev_data[2]),
    .data_out(dev_data[3]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  \$paramod$9347947338dd2dfd9e49dd4a7c49f3c6949c9061\ctrl_block  blk_pmos_dual_I (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[161:156]),
    .data_in(dev_data[0]),
    .data_out(dev_data[1]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__clkbuf_16 \buf_in_I[0]  (
    .A(enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(g_enable)
  );
  sky130_fd_sc_hd__clkbuf_16 \buf_in_I[1]  (
    .A(rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(g_rst_n)
  );
  sky130_fd_sc_hd__clkbuf_16 \buf_in_I[2]  (
    .A(clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(g_clk)
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_mid_I[0]  (
    .A(asw_data[26]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(mid_data[0])
  );
  sky130_fd_sc_hd__clkbuf_4 \buf_mid_I[1]  (
    .A(mid_data[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(mid_data[1])
  );
  sky130_fd_sc_hd__clkbuf_16 buf_out_I (
    .A(dev_data[7]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(data_out)
  );
  sky130_fd_sc_hd__decap_8 decap_14_0_I (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 decap_14_1_I (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 decap_24_1_I (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 decap_2_0_I (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 decap_2_1_I (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 decap_36_1_I (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_b1[0].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_b1[0].decap_12_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_b1[0].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_b2[0].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_b2[1].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_b2[2].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_b2[3].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_b2[4].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_b2[5].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_e1[0].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_e1[0].decap_12_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_e1[0].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_e1[0].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_e1[0].decap_9_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_e2[0].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_e2[0].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_e2[1].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_e2[1].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_e2[2].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_e2[2].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_e2[3].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_e2[3].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_e2[4].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_e2[4].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_e2[5].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_e2[5].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_m2[0].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_m2[0].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_m2[0].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_m2[1].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_m2[1].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_m2[1].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_m2[2].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_m2[2].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_m2[2].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_m2[3].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_m2[3].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_m2[3].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \decap_m2[4].decap_1_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_m2[4].decap_22_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \decap_m2[4].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[0].decap_0_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[0].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[0].decap_14_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[0].decap_14_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[0].decap_26_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[0].decap_26_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[0].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[0].decap_34_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[1].decap_0_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[1].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[1].decap_14_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[1].decap_14_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[1].decap_26_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[1].decap_26_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[1].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[1].decap_34_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[2].decap_0_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[2].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[2].decap_14_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[2].decap_14_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[2].decap_26_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[2].decap_26_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[2].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[2].decap_34_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[3].decap_0_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[3].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[3].decap_14_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_12 \decap_p[3].decap_14_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[3].decap_26_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[3].decap_26_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[3].decap_34_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_6 \decap_p[3].decap_34_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__diode_2 \diode_in_I[0]  (
    .DIODE(g_enable),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__diode_2 \diode_in_I[1]  (
    .DIODE(g_rst_n),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__diode_2 \diode_in_I[2]  (
    .DIODE(g_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__clkdlybuf4s50_2 dly_mid_I (
    .A(mid_data[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR),
    .X(dev_data[0])
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[0].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[5:0]),
    .data_in(asw_data[0]),
    .data_out(asw_data[1]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[0].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[0].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[0].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[0].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[0].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[0].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[0].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[0].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[0].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[0].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[0].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[10].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[65:60]),
    .data_in(asw_data[10]),
    .data_out(asw_data[11]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[10].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[10].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[10].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[10].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[10].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[10].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[10].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[10].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[10].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[10].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[10].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[11].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[71:66]),
    .data_in(asw_data[11]),
    .data_out(asw_data[12]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[11].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[11].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[11].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[11].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[11].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[11].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[11].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[11].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[11].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[11].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[11].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[12].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[77:72]),
    .data_in(asw_data[12]),
    .data_out(asw_data[13]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[12].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[12].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[12].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[12].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[12].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[12].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[12].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[12].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[12].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[12].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[12].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[13].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[83:78]),
    .data_in(asw_data[13]),
    .data_out(asw_data[14]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[13].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[13].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[13].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[13].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[13].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[13].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[13].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[13].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[13].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[13].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[13].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[14].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[89:84]),
    .data_in(asw_data[14]),
    .data_out(asw_data[15]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[14].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[14].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[14].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[14].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[14].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[14].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[14].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[14].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[14].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[14].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[14].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[15].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[95:90]),
    .data_in(asw_data[15]),
    .data_out(asw_data[16]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[15].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[15].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[15].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[15].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[15].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[15].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[15].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[15].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[15].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[15].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[15].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[16].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[101:96]),
    .data_in(asw_data[16]),
    .data_out(asw_data[17]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[16].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[16].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[16].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[16].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[16].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[16].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[16].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[16].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[16].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[16].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[16].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[17].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[107:102]),
    .data_in(asw_data[17]),
    .data_out(asw_data[18]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[17].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[17].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[17].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[17].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[17].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[17].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[17].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[17].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[17].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[17].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[17].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[18].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[113:108]),
    .data_in(asw_data[18]),
    .data_out(asw_data[19]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[18].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[18].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[18].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[18].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[18].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[18].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[18].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[18].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[18].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[18].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[18].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[19].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[119:114]),
    .data_in(asw_data[19]),
    .data_out(asw_data[20]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[19].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[19].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[19].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[19].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[19].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[19].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[19].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[19].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[19].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[19].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[19].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[1].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[11:6]),
    .data_in(asw_data[1]),
    .data_out(asw_data[2]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[1].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[1].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[1].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[1].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[1].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[1].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[1].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[1].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[1].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[1].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[1].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[20].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[125:120]),
    .data_in(asw_data[20]),
    .data_out(asw_data[21]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[20].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[20].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[20].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[20].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[20].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[20].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[20].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[20].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[20].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[20].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[20].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[21].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[131:126]),
    .data_in(asw_data[21]),
    .data_out(asw_data[22]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[21].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[21].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[21].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[21].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[21].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[21].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[21].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[21].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[21].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[21].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[21].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[22].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[137:132]),
    .data_in(asw_data[22]),
    .data_out(asw_data[23]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[22].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[22].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[22].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[22].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[22].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[22].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[22].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[22].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[22].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[22].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[22].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[23].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[143:138]),
    .data_in(asw_data[23]),
    .data_out(asw_data[24]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[23].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[23].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[23].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[23].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[23].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[23].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[23].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[23].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[23].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[23].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[23].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[24].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[149:144]),
    .data_in(asw_data[24]),
    .data_out(asw_data[25]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[24].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[24].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[24].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[24].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[24].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[24].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[24].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[24].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[24].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[24].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[24].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[25].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[155:150]),
    .data_in(asw_data[25]),
    .data_out(asw_data[26]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[25].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[25].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[25].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[25].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[25].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[25].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[25].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[25].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[25].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[25].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[25].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[2].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[17:12]),
    .data_in(asw_data[2]),
    .data_out(asw_data[3]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[2].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[2].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[2].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[2].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[2].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[2].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[2].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[2].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[2].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[2].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[2].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[3].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[23:18]),
    .data_in(asw_data[3]),
    .data_out(asw_data[4]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[3].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[3].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[3].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[3].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[3].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[3].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[3].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[3].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[3].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[3].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[3].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[4].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[29:24]),
    .data_in(asw_data[4]),
    .data_out(asw_data[5]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[4].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[4].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[4].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[4].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[4].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[4].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[4].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[4].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[4].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[4].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[4].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[5].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[35:30]),
    .data_in(asw_data[5]),
    .data_out(asw_data[6]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[5].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[5].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[5].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[5].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[5].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[5].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[5].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[5].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[5].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[5].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[5].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[6].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[41:36]),
    .data_in(asw_data[6]),
    .data_out(asw_data[7]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[6].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[6].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[6].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[6].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[6].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[6].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[6].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[6].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[6].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[6].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[6].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[7].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[47:42]),
    .data_in(asw_data[7]),
    .data_out(asw_data[8]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[7].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[7].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[7].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[7].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[7].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[7].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[7].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[7].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[7].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[7].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[7].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[8].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[53:48]),
    .data_in(asw_data[8]),
    .data_out(asw_data[9]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[8].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[8].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[8].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[8].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[8].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[8].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[8].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[8].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[8].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[8].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[8].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  \$paramod$7346c0698628a0883814e78de20de531bf9bdd44\ctrl_block  \genblk1[9].blk_I  (
    .VDPWR(VDPWR),
    .VGND(VGND),
    .clk(g_clk),
    .ctrl_out(ctrl_out[59:54]),
    .data_in(asw_data[9]),
    .data_out(asw_data[10]),
    .enable(g_enable),
    .rst_n(g_rst_n)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[9].decap_0_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_8 \genblk1[9].decap_0_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[9].decap_36_0_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[9].decap_36_1_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[9].decap_36_2_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[9].decap_36_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[9].decap_36_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_4 \genblk1[9].decap_36_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[9].decap_6_3_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[9].decap_6_4_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  sky130_fd_sc_hd__decap_3 \genblk1[9].decap_6_5_I  (
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDPWR),
    .VPWR(VDPWR)
  );
  assign asw_data[0] = data_in;
endmodule
